spring.application.name=soap-demo
spring.webservices.path=/ws
spring.webservices.wsdl-locations=classpath:/META-INF/schemas/
spring.webservices.servlet.init.transformWsdlLocations=true
spring.webservices.servlet.init.transformSchemaLocations=true
